# Generated by Django 4.2.3 on 2023-08-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'products'},
        ),
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
